# Generated by Django 5.1.7 on 2026-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(db_index=True, max_length=10)),
                ('coordinate', models.IntegerField(db_index=True)),
                ('ref', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('gt', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Genotype',
                'verbose_name_plural': 'Genotypes',
                'indexes': [models.Index(fields=['chromosome', 'coordinate'], name='api_genotyp_chromos_35a7c4_idx')],
            },
        ),
    ]
